[package]
name = "ravro"
version = "0.1.0"
authors = ["Guy Waldman <guywald1@gmail.com>"]
edition = "2018"

[dependencies]
avro-rs = "0.6"
failure = "0.1.5"
glob = "0.3.0"
prettytable-rs = "0.8"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.2"