[package]
name = "ravro"
version = "0.1.0"
authors = ["Guy Waldman <guywald1@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"
prettytable-rs = "0.8"
avro-rs = "0.6"
regex = "1"
failure = "0.1.5"
serde = { version = "1.0", features = ["derive"] }